In [1]:
import torch

## Create Tensor

In [3]:
x = torch.empty(3) # 1D vector with 3 elements
print(x)

tensor([1.4013e-44, 0.0000e+00, 0.0000e+00])


In [5]:
x = torch.empty(2,3) # 2D vector with 3 elements in each
print(x)

tensor([[0.0000e+00, 0.0000e+00, 1.8754e+28],
        [4.1586e-05, 8.4483e+20, 1.0414e-11]])


In [8]:
x = torch.rand(2,2) # Random 2D tensor
print(x)

tensor([[0.1190, 0.6628],
        [0.4868, 0.6041]])


In [9]:
x = torch.zeros(2,2) # All zeros
print(x)

tensor([[0., 0.],
        [0., 0.]])


In [10]:
x = torch.ones(2,2) # All ones
print(x)

tensor([[1., 1.],
        [1., 1.]])


In [15]:
x = torch.ones(2,2, dtype=torch.int) # You can set the dtype by setting 
print(x.dtype)

torch.float16


In [16]:
x = torch.ones(2,2, dtype=torch.int) # You can set the dtype by setting 
print(x.size())

torch.Size([2, 2])


In [17]:
x = torch.tensor([2.5, 0.1]) # Create from a list
print(x)

tensor([2.5000, 0.1000])


## Operation

In [20]:
x = torch.rand(2,2)
y = torch.rand(2,2)
print(x)
print(y)

z = x + y # Element-wise addition
z = torch.add(x,y) # Same as x + y
print(z)

y.add_(x) # In-place Addition.  Set y to be x+y
print(y)

tensor([[0.0115, 0.4057],
        [0.8638, 0.7622]])
tensor([[0.8988, 0.9610],
        [0.9968, 0.4154]])
tensor([[0.9103, 1.3667],
        [1.8606, 1.1777]])
tensor([[0.9103, 1.3667],
        [1.8606, 1.1777]])


In PyTorch, every function with a trailing underscore will do a in-place operation.

In [25]:
z = x - y # Note that y here is changed by the in-placde operation above.
z = torch.sub(x,y) # Same as x - y
print(z)

tensor([[-0.8988, -0.9610],
        [-0.9968, -0.4154]])


In [30]:
z = torch.mul(x,y) # Element-wise multiplication z = x * y
print(z)

y.mul_(x) # y = y * x. Again in-place addition here.

z = torch.div(x, y) # Element-wise division. z = x / y
print(z)

tensor([[0.0104, 0.5544],
        [1.6071, 0.8977]])
tensor([[1.0986, 0.7317],
        [0.5375, 0.8491]])


In [49]:
# Slicing Operation
x = torch.rand(5,3)
print(x)
print('')
print(x[1,:])
print('')
print(x[1,1])
print(x[1,1].item()) # If you have only one item in your tensor, you have retrieve the value out with .item()

tensor([[0.5477, 0.3944, 0.3828],
        [0.6426, 0.9040, 0.7911],
        [0.6464, 0.2564, 0.3911],
        [0.3102, 0.8791, 0.0309],
        [0.7390, 0.2088, 0.6210]])

tensor([0.6426, 0.9040, 0.7911])

tensor(0.9040)
0.9040480852127075


In [57]:
# Reshaping
x = torch.rand(4,4)
print(x)
print('\n')
y = x.view(-1) #.view is the same as the .reshape in pandas.
print(y)
print('\n')
y = y.view(2,-1)
print(y)
print(y.size())

tensor([[0.3347, 0.2766, 0.3431, 0.1502],
        [0.8926, 0.1400, 0.3400, 0.5738],
        [0.6633, 0.1542, 0.8942, 0.5913],
        [0.7100, 0.7845, 0.9933, 0.6279]])


tensor([0.3347, 0.2766, 0.3431, 0.1502, 0.8926, 0.1400, 0.3400, 0.5738, 0.6633,
        0.1542, 0.8942, 0.5913, 0.7100, 0.7845, 0.9933, 0.6279])


tensor([[0.3347, 0.2766, 0.3431, 0.1502, 0.8926, 0.1400, 0.3400, 0.5738],
        [0.6633, 0.1542, 0.8942, 0.5913, 0.7100, 0.7845, 0.9933, 0.6279]])
torch.Size([2, 8])


## Converting Between Numpy and Torch Tensor

In [58]:
import numpy as np

In [65]:
a = torch.ones(5)
print(a)
b = a.numpy() # convert to numpy
print(b)
print(type(b))

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>


Note that if you are using the CPU version, the tensor and the converted numpy will share the same memory location. Thus, if we hange one of the variable, the other one will change accordingly.

In [66]:
a.add_(1)
print(a)
print('')
print(b)

tensor([2., 2., 2., 2., 2.])

[2. 2. 2. 2. 2.]


In [72]:
a = np.ones(5)
print(a)
b = torch.from_numpy(a) # convert to torch
print(b)
print(type(b))

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
<class 'torch.Tensor'>


In [74]:
# Similar memory location issue happens here.
a += 1
print(a)
print('')
print(b)

[2. 2. 2. 2. 2.]

tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [75]:
# Create Tensor on GPU
if torch.cuda.is_available():
    device = torch.device('cuda')
    x = torch.ones(5, device=device) # Create the tensor on GPU 
    
    # Another why to create tensor on GPU
    y = torch.ones(5)
    y = y.to(device) # Move tensor to GPU from CPU
    
    z = x * y
    # z.numpy() will raise error since numpy can only handle CPU tensor
    z = z.to("cpu").numpy() # Move to CPU and then convert to numpy

In [79]:
x = torch.ones(5, requires_grad=True) 
x 
# If you want to optimize this variable later, 
# you need to set requires_grad = True

tensor([1., 1., 1., 1., 1.], requires_grad=True)